---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: default
spec:
  instances: 3
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.2.1
  affinity:
    nodeSelector:
      # use all the same arch
      kubernetes.io/arch: amd64
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi
  enableSuperuserAccess: true
  monitoring:
    enablePodMonitor: true
    # Ref: https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    podMonitorMetricRelabelings:
      - {
          sourceLabels: ["cluster"],
          targetLabel: cnpg_cluster,
          action: replace,
        }
      - { regex: cluster, action: labeldrop }
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 2
      destinationPath: s3://databases/
      endpointURL: https://s3.${SECRET_DOMAIN:=internal}
      serverName: immich-v2
      s3Credentials:
        accessKeyId:
          name: minio-immich-pgsql
          key: minio_s3_access_key
        secretAccessKey:
          name: minio-immich-pgsql
          key: minio_s3_secret_access_key
  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      source: &previousCluster immich-v1
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
