---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jellyfin
  namespace: default
  labels:
    app.kubernetes.io/name: &name jellyfin
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-jellyfin
  capacity:
    storage: 2Gi # this number doesn't matter
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_PATH}/jellyfin"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # this number doesn't matter
  storageClassName: nfs-jellyfin

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-csi
