---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-matter-hub-secret
  namespace: default
stringData:
  HAMH_HOME_ASSISTANT_URL: "https://home.${SECRET_DOMAIN}"
  HAMH_HOME_ASSISTANT_ACCESS_TOKEN: ${HAMH_ACCESS_TOKEN}
