---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre-flux
  - ./namespace.yaml
  # Post-flux
  - ./coredns/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./kubelet-csr-approver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
