---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitwarden-eso-provider
  namespace: kube-system
spec:
  interval: 2h
  url: https://small-hack.github.io/bitwarden-eso-provider
