---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-eso-provider
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: bitwarden-eso-provider
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: bitwarden-eso-provider
        namespace: kube-system
      interval: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    bitwarden_eso_provider:
      auth:
        password: ${BW_PASSWORD}
        clientSecret: ${BW_CLIENTSECRET}
        clientID: ${BW_CLIENTID}
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
    nodeSelector:
      kubernetes.io/arch: amd64
    network_policy:
      enabled: false
