---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opn-plugins-signing-key
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        private_key: |-
          {{ .privateKey }}
  refreshInterval: 15m
  data:
    - secretKey: privateKey
      remoteRef:
        key: opn-plugins signing key
        property: private_key
