---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: ${VPN_SERVICE_PROVIDER:=vpn}
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRESHARED_KEY
    - secretKey: FIREWALL_VPN_INPUT_PORTS
      remoteRef:
        key: vpn-gateway-secrets
        property: FIREWALL_VPN_INPUT_PORTS
