---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      qbittorrent:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-secret

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: network/gateway-network-client-pod-qbittorrent@vpn-gw-veth0
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - 192.168.24.253
            searches:
              - downloads.svc.cluster.local
              - svc.cluster.local
              - cluster.local
            options:
              - name: ndots
                value: "5"

        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.4
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 150m
                memory: 2048Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4
            env:
              GLUETUN_CONTROL_SERVER_HOST: vpn-gateway.vpn.svc.cluster.local
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        hosts:
          - host: qbittorrent.${SECRET_DOMAIN:=internal}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config
      downloads:
        type: nfs
        server: ${SECRET_NFS_SERVER:=nfs.internal}
        path: ${SECRET_NFS_DATA_PATH:=temp}
        globalMounts:
          - path: /downloads
            subPath: torrents
