---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name qbittorrent
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-qbittorrent
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_PATH}/qbittorrent-config"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-qbittorrent
