# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json

  - repo: local
    hooks:
      - id: sops
        name: Check for unencrypted SOPS secrets
        description: detects the presence of SOPS secrets that are unencrypted or are encrypted with the wrong key(s).
        language: docker_image
        entry: |
          --entrypoint /bin/sh mozilla/sops:v3.7-alpine -c '
          OUT=""
          EXIT=0
          for file in "$@"; do
            if ! out="$(sops updatekeys "$file" 2>&1 1>/dev/null)"; then
              OUT="$OUT\n$out"
              EXIT=1
            fi
          done
          echo -ne "$OUT" | sed "s|.*Syncing keys for file /src/||g"
          exit "$EXIT"' sh
        exclude: |
          (?x)^(
            .sops.yaml|
            .*\.j2
          )$
        files: |
          (?x)^(
            .*\.sops\..*|
            kubernetes/flux/vars/cluster.*\.yaml
          )$
