---
creation_rules:
  - # encrypt talos config
    path_regex: kubernetes/talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68"
  - # encrypt talos helper config
    path_regex: kubernetes/talos/talconfig.yaml
    key_groups:
      - age:
          - "age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68"
  - path_regex: kubernetes/flux/vars/.*\.ya?ml
    encrypted_regex: "((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))"
    key_groups:
      - age:
          - "age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68"
  - # IMPORTANT: encrypt terraform
    path_regex: terraform/.*/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68"
