---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MINIO_ROOT_USER: |-
          {{ .username }}
        MINIO_ROOT_PASSWORD: |-
          {{ .password }}
  refreshInterval: 15m
  data:
    - secretKey: username
      remoteRef:
        key: minio credentials
        property: username
    - secretKey: password
      remoteRef:
        key: minio credentials
        property: password
