apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
  namespace: storage
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER:=192.168.1.1}
    path: "${SECRET_NFS_PATH:=/data}/s3"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi
