---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-server
  namespace: default
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      immich-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          initdb:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2
            env:
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: username
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: password
              - name: INIT_POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: host
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: immich-database-superuser
                    key: password
              - name: INIT_POSTGRES_DBNAME
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: dbname
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.103.1
            command: /bin/sh
            args:
              - ./start-server.sh
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 1000Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - configMapRef:
                  name: immich-config
            env:
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: uri
    service:
      main:
        controller: immich-server
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host photos.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      data:
        enabled: true
        existingClaim: immich-data
        globalMounts:
          - path: /usr/src/app/upload
