---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-secret
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        github_app_id: |-
          {{ .appId }}
        github_app_installation_id: |-
          {{ .installationId }}
        github_app_private_key: |-
          {{ .privateKey }}
  refreshInterval: 15m
  data:
    - secretKey: appId
      remoteRef:
        key: github runner app credentials
        property: app_id
    - secretKey: installationId
      remoteRef:
        key: github runner app credentials
        property: installation_id
    - secretKey: privateKey
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: github runner app credentials
