---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${VPN_SERVICE_PROVIDER:=openvpn}
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: ${VPN_SERVICE_PROVIDER:=openvpn}
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        SHADOWSOCKS_PASSWORD: "{{ .SHADOWSOCKS_PASSWORD }}"
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESS }}"
        WIREGUARD_PRESHARED_KEY: "{{ .WIREGUARD_PRESHARED_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
  # dataFrom:
  #   - key: vpn-gateway-secrets
  data:
    - secretKey: SHADOWSOCKS_PASSWORD
      remoteRef:
        key: vpn-gateway-secrets
        property: SHADOWSOCKS_PASSWORD
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRESHARED_KEY
    - secretKey: WIREGUARD_ADDRESS
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_ADDRESS
