apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd21sOUt4bTlETTQvb1NM
            SEJoT21aeVlhMW5VN1FiTURmaVNQRmZ5ZVhVCjgyMC9BdkFCeGV6NFJVbHVyL2Uy
            cjM3aHI0WXFQTElsSmM3WmFrU1lRc3cKLS0tIGd3SytOeDhrTTdiamZqWWdDNlhT
            QmE3Zkw4MUVzc2VPa1BhRFVqUkF0Qk0KyOdvuNgzxm8HG3Z5p+2FjAAbKOgHRiO2
            Hd3avCrdlxYdEZbKhkHUw6iJrjwpqq47V/1mm07uHjIkekcLNEmelg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-25T21:05:16Z"
    mac: ENC[AES256_GCM,data:6irsYtHtS+UJSnZP1xUpZkqbBW9DHS5215sjinWh47F5+YNBa0N35mrWhXqFWioPgY/jXeLgXXqOelRYgYnKJ6DhEQxEsfX8eqyYAygTZ1Vu9f272HOVk/iqyTjqVk9F9kWXjXwsdnu1AbNiedyQtFfhoYCWJH4uoI5jnLu/3C8=,iv:xs06UFJfsUZJIlwVW9AmHaC3Ejl2uQJRF66FIL6Wo2w=,tag:dycaVNo0NJDCHlqcUR4pUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
