---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wallos
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      wallos:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          wallos:
            image:
              repository: bellamy/wallos
              tag: 2.48.0
            env:
              TZ: ${TIMEZONE:=US}
            resources:
              requests:
                cpu: 50m
                memory: 256Mi

    service:
      app:
        controller: wallos
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host subs.${SECRET_DOMAIN:=internal}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-csi
        retain: true
        globalMounts:
          - path: /var/www/config/db
            readOnly: false
