---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-immich
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  interval: 30m
  retryInterval: 5m
  timeout: 10m
  dependsOn:
    - name: cluster-apps-external-secrets
    - name: dragonfly-cluster
    - name: cluster-apps-csi-driver-nfs
