---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP:-unknown}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP} Exposure"
        group: internal-guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
      - name: "${APP}"
        group: internal
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}"
        interval: 1m
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
