---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: openbao-unseal
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        unseal_key: "{{ .unseal_key }}"
  data:
    - secretKey: unseal_key
      remoteRef:
        key: openbao credentials
        property: unseal_key
