---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: loki-bucket
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: minio-tf-logs
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: minio-tf-logs
        property: password
