---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-gateway
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: vpn-gateway-credentials
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: vpn-gateway-secrets
        property: WIREGUARD_PRESHARED_KEY
    - secretKey: VPN_FORWARDED_PORT
      remoteRef:
        key: vpn-gateway-secrets
        property: FIREWALL_VPN_INPUT_PORTS
