---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-network-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: node-network-operator
      version: 0.0.8
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: soliddowant-charts
        namespace: flux-system

  values:
    webhook:
      tls:
        certManager:
          enabled: true
          issuerRef:
            name: node-network-operator-issuer
            kind: Issuer
