---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./grafana/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./unpoller/ks.yaml
  - ./victoriametrics/ks.yaml
  - ./vector/ks.yaml
