---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: productivity
labels:
  - pairs:
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/part-of: forgejo
resources:
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./database
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/guarded
