---
apiVersion: v1
kind: Namespace
metadata:
  name: productivity
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations:
    # allow VolSync movers to run as root (wallos stores root-owned data)
    volsync.backube/privileged-movers: "true"
