apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:9a8MFOsJWl36VR7rYOGb56Ygo+WxvKSrrOuAafTwcaR3fgoi+Q7E3Evfgz9IS9qwTOzhxXsz/cUXAZdWwithQ4JMfD9IXtbPNg==,iv:Yes7lvX2YclrpTSAwBr40wSW7E5wFOPL11Rd2uY4D7A=,tag:ujkVLMGDQ54lJXxdY9JBCw==,type:comment]
    #ENC[AES256_GCM,data:2tS2ix7b9zhHuN5yxYEjAAUtFvOO8FDHz5vhfhFls2U7LokMB4foTRE3WJr03ja861XnpH0LVT6tkUt+c/BrfhLhgAw=,iv:n1IyVvGwVLxE1M54fWbjoHf25osUICSssT50XEOgnTg=,tag:XlsthA322IOkUsjZUHGiaA==,type:comment]
    #ENC[AES256_GCM,data:NBpiWdtQRJeYWPhxD0JPVG4Xrgar7zbyXcbt6WzmCiX4J1ifu71I/B2r,iv:j2Xp03p0mkfdDfITUYn75OjwsBkQqE4um/yaiHSQdTA=,tag:Rzive4nIMCZ2vR1rU+HYzw==,type:comment]
    #
    #ENC[AES256_GCM,data:Vko6QOMb+btpgjf6Ri5llkLivseVXx4whEGkffeKwVhOb+jiYT0+Tmd+lhkwVNwDUC27nzUSGUnLWgozZGPJX8gxbz2g3mnzXg==,iv:Q+/l3UQpYnvVtlpYV1jIqPBAmDSHVzNnePnXkufen9U=,tag:mPvHxN684iYKXO1OCVDKIw==,type:comment]
    #ENC[AES256_GCM,data:uZiwTZ8gK6iAYVxn4tt3cZnYYRVaCMTzWHGejWnsQmhTor8/ePPc8q+5WpkDusIz5zgsuFgqj+vbGnZJGKu9VGn9Vac=,iv:7437PeXu/I6FiS90+IWZrOWuoXL3XTiIjQnUpsM2Rb8=,tag:9UmJ84PJig3dpJEzwe7Fog==,type:comment]
    SECRET_NODE_FOYER_DELL_MFF: ENC[AES256_GCM,data:xo6qVZYf6ANbMdHvi/Y=,iv:camVaTnvvVOszB14ztLxQtPMD3UYNDQ9M2Zjnj/y4w0=,tag:L0N26KJG4+k6TkZWDn7Dgw==,type:str]
    SECRET_NODE_BASEMENT_DELL_SFF: ENC[AES256_GCM,data:MukGPQG7oeh0p6QkVCg=,iv:tiNHx6NW8KrMimu1nL/fbsn/juaeA9HADN89HIzOm74=,tag:eOQn02SXsV/l5+xb3vNqfw==,type:str]
    SECRET_NODE_BASEMENT_RPI4_CHOCOLATE: ENC[AES256_GCM,data:cu/rRIixSa0oeZl9E7c=,iv:zxA3Mb3RyADqJ75DFK+4m0gUsEJS+kZp5j5HcA9eJu4=,tag:xm7pfB1ZizSa2zSbyovq8w==,type:str]
    SECRET_NODE_BASEMENT_RPI4_PEACH: ENC[AES256_GCM,data:XEU6LyG660EOh4Ic+Ss=,iv:xkwrZwH/bry6SyB3rpoEpeNw8TqQt+Nwz2QB/DK0qaY=,tag:Y1tf69/1Uzz9ZD7kAmpiqQ==,type:str]
    SECRET_NODE_FOYER_DELL_3040: ENC[AES256_GCM,data:hJsCmNtep0r1Y7La54c=,iv:4/xVeFvKOtZ8kociwe1R1c6kfo8sGm6e+vHBHxroyGo=,tag:TZvnIxD9M4Ek0m0jxQTyHw==,type:str]
    SECRET_NODE_FOYER_HP_800G3: ENC[AES256_GCM,data:2khGD5HU+2Y/ZR1mc+g=,iv:lIaS7htGCXrCrWgttdsxZCKQiV+ejF0ZRq5K78nsj1M=,tag:SFUv6YnUDLjngeYGzhh9GQ==,type:str]
    SECRET_NODE_BASEMENT_LENOVO_M910Q: ENC[AES256_GCM,data:mJoHrBtBz9nSQDOQVbQ=,iv:dgwsIKLT676OA8G5Xnl7tJsmFBVvdZjNrRtYy39qNNo=,tag:U5IanbTASzkyfCvSH9RmFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZEJnZ1FYMFZKOFcrMTlX
            ZFo4c0EzdjBLTHpDRmhyNHRzWUVuL2lnZTBZCm9mRE9IZldsUGYwNGdxU3BHdkRD
            OGd3K0FOSjQvV2tkOSttSGxoajRRMkEKLS0tIE1IVTNiTHY4VzJDK1NobGgyWEFG
            aGhZNytjZkRLQ3NNY3ZrbGtBRWRJNm8KxWxlqSR2iYNIRzkRieHVBykViLZ2RxhN
            ie2qXb9EdRJmtQ0QJZPz0CIwDttWBAI89zxr11lIkWqG48EJWdDP4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-10T14:45:36Z"
    mac: ENC[AES256_GCM,data:5C/1jzZxI0v3CAZ8FqzS5jgvyjg3e6KT5CFo1FHDBPVumze3xaOea7MF+pc4xSsPs3kVgTY2CCojXM/5kFt5my94IqFF+VC5MLUaKHSwtV5gcTJstbHgHC3Xjmq0NIpNsoiZg0UFdYpo8ZjYOXGZl5a7MnWP8FjXVbDz6gND+Hk=,iv:NFhdAKvKHKvcZPnXmp6KTfJ5wr4N4SVpHk7fWTtyd8o=,tag:6dp/dr+RJLpbAIN3CtNDlg==,type:str]
    version: 3.13.3
