---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # preflux
  - ./namespace.yaml
  # post-flux
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./headscale/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./nginx/ks.yaml
  - ./vpn-gateway/ks.yaml
