---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victorialogs
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.11.13
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: observability
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: kube-system
  values:
    # values for victoria-logs.
    server:
      persistentVolume:
        # -- Create/use Persistent Volume Claim for server component. Empty dir if false
        enabled: true

        # -- StorageClass to use for persistent volume. Requires server.persistentVolume.enabled: true. If defined, PVC created automatically
        storageClassName: nfs-csi

        # -- Size of the volume. Should be calculated based on the logs you send and retention policy you set.
        size: 10Gi
