---
apiVersion: v1
kind: Service
metadata:
  name: vmsingle-lb
  namespace: observability
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: 8428
  selector:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/instance: vm-victoria-metrics-k8s-stack
    app.kubernetes.io/name: vmsingle
    managed-by: vm-operator
