---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallos
  namespace: productivity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: wallos-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: "{{ .client_id }}"
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: authentik-client-wallos
        property: username
    - secretKey: client_secret
      remoteRef:
        key: authentik-client-wallos
        property: password
