---
data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686

enrichment_tables:
  geoip_table:
    type: geoip
    path: /usr/share/GeoIP/GeoLite2-City.mmdb

#
# Sources
#

sources:
  journald_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6000

  kubernetes_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6010

  internal_metrics:
    type: internal_metrics
#
# Transforms
#

transforms:
  kubernetes_remap:
    type: remap
    inputs: ["kubernetes_source"]
    source: |
      # Standardize 'app' index
      .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      # Drop pod_labels
      del(.pod_labels)
      # extract json
      .log = parse_json(.message) ?? .message
      del(.message)

#
# Sinks
#

sinks:
  journald:
    inputs: ["journald_source"]
    type: elasticsearch
    endpoints:
      - http://victorialogs-victoria-logs-single-server.observability.svc.cluster.local.:9428/insert/elasticsearch
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    # query:
    #   debug: "1"
    request:
      headers:
        VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
        VL-Time-Field: timestamp

  kubernetes:
    inputs: ["kubernetes_remap"]
    type: elasticsearch
    endpoints:
      - http://victorialogs-victoria-logs-single-server.observability.svc.cluster.local.:9428/insert/elasticsearch
    api_version: v8
    compression: gzip
    healthcheck:
      enabled: false
    mode: bulk
    # query:
    #   debug: "1"
    request:
      headers:
        VL-Msg-Field: message,msg,_msg,log.msg,log.message,log
        VL-Stream-Fields: stream,kubernetes.pod_name,kubernetes.container_name,kubernetes.pod_namespace
        VL-Time-Field: timestamp

  exporter:
    address: 0.0.0.0:9090
    inputs:
      - internal_metrics
    type: prometheus_exporter
