---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: victoriametrics
      namespace: observability
  values:
    fullnameOverride: *app
    config:
      devices:
        - /dev/sda
        - /dev/nvme0n1
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
