---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mealie
  namespace: default
  labels:
    app.kubernetes.io/name: &name mealie
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-mealie
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER:=192.168.1.1}
    path: "${SECRET_NFS_PATH:=/data}/mealie"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-mealie
