---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: immich-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: immich credentials
        property: pg_username
    - secretKey: password
      remoteRef:
        key: immich credentials
        property: pg_password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-immich-pgsql
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        minio_s3_access_key: |-
          {{ .minio_user }}
        minio_s3_secret_access_key: |-
          {{ .minio_secret }}
  refreshInterval: 15m
  data:
    - secretKey: minio_user
      remoteRef:
        key: minio-tf-databases
        property: username
    - secretKey: minio_secret
      remoteRef:
        key: minio-tf-databases
        property: password
