---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: immich
      app.kubernetes.io/part-of: immich
resources:
  - ./configmap.yaml
  - ./database
  - ./externalsecret.yaml
  - ./pvc.yaml
  - ./server
  - ./microservices
  - ./machine-learning
