---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich
  namespace: default
  labels:
    app.kubernetes.io/name: &name immich
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-immich
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "/volume1/immich"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-immich
