---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: not-vlan
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "not-vlan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.1",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "${LAN_CIDR}", "gw": "${LAN_GATEWAY}" },
              { "dst": "${IOT_CIDR}", "gw": "${LAN_GATEWAY}" }
            ]
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
