---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: home-assistant-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
  data:
    - secretKey: HASS_ELEVATION
      remoteRef:
        key: home assistant
        property: HASS_ELEVATION
    - secretKey: HASS_LATITUDE
      remoteRef:
        key: home assistant
        property: HASS_LATITUDE
    - secretKey: HASS_LONGITUDE
      remoteRef:
        key: home assistant
        property: HASS_LONGITUDE
