---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.7.3
            env:
              TZ: America/New_York
              HASS_HTTP_TRUSTED_PROXY_1: ${SERVICE_CIDR:=127.0.0.1}
              HASS_HTTP_TRUSTED_PROXY_2: ${NODE_CIDR:=10.0.0.0/8}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          affinity:
            nodeAffinity:
              # only schedule on nodes with the zwave label
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
          annotations:
            # printf '02:00:00:%02X:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256))
            # 02 indicates a locally administered address
            k8s.v1.cni.cncf.io/networks: |
              [
                {
                "name":"iot-vlan",
                "interface": "eth0.50",
                "namespace": "network",
                "ips": ["${HOME_ASSISTANT_IOT_CIDR_V4:=192.168.1.3}"],
                "mac": "02:00:00:B5:46:C4"
                }
              ]
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: "vscode-icons:file-type-homeassistant"
        hosts:
          - host: &host "home.${SECRET_DOMAIN:=internal}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant
        globalMounts:
          - path: /config
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir
