---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-assistant
  namespace: default
  labels:
    app.kubernetes.io/name: &name home-assistant
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-home-assistant
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER:=192.168.1.1}
    path: "${SECRET_NFS_PATH:=/data}/home-assistant"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-home-assistant
