---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games

resources:
  - helmrelease.yaml

configMapGenerator:
  - name: mincraft-router-values
    namespace: game-servers
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
