---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OAUTH_CLIENT_ID: "{{ .client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: authentik-client-open-webui
        property: username
    - secretKey: client_secret
      remoteRef:
        key: authentik-client-open-webui
        property: password
